package com.jobwork.v2;

import android.app.AlertDialog;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import androidx.activity.ComponentActivity;
import androidx.annotation.Nullable;
import com.google.android.material.button.MaterialButton;
import com.google.android.material.card.MaterialCardView;
import com.google.android.material.textfield.TextInputEditText;
import com.google.android.material.textfield.TextInputLayout;
import com.google.firebase.FirebaseApp;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.*;
import java.util.*;

public class MainActivity extends ComponentActivity {
    LinearLayout root, content; FirebaseAuth auth; FirebaseFirestore db; String role="customer"; String uid=""; String currentName="User";
    int BLUE=Color.rgb(36,59,219), BG=Color.rgb(246,248,252), TEXT=Color.rgb(21,26,45), MUTED=Color.rgb(102,112,133);
    final String[] AREAS={"Ambattur","Guindy","Padi","Thirumudivakkam","Porur","Sriperumbudur","Oragadam","Chromepet","Tambaram","Maraimalai Nagar","Avadi","Red Hills"};
    final String[] SERVICES={"CNC Machining","VMC Machining","Turning","Wire EDM","Mould & Tool","Grinding","Fabrication","Welding"};
    @Override public void onCreate(Bundle b){super.onCreate(b); if(!initFirebase()){setupError();return;} auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance(); if(auth.getCurrentUser()!=null){uid=auth.getCurrentUser().getUid();loadRole();}else login();}
    boolean initFirebase(){try{return !FirebaseApp.getApps(this).isEmpty()||FirebaseApp.initializeApp(this)!=null;}catch(Exception e){return false;}}
    void setupError(){base("JobWork V2"); addText("Firebase could not be initialized",24,TEXT,true); addText("Check that app/google-services.json exists and belongs to package com.jobwork.v2, then rebuild.",16,MUTED,false);}
    void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG); setContentView(root); TextView bar=text(title,22,Color.WHITE,true); bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(20,0,20,0);bar.setBackgroundColor(BLUE);root.addView(bar,new LinearLayout.LayoutParams(-1,64));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(16,18,16,24);ScrollView s=new ScrollView(this);s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));}
    TextView text(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,8,0,8);if(bold)t.setTypeface(null,Typeface.BOLD);return t;}
    TextView addText(String s,float size,int color,boolean bold){TextView t=text(s,size,color,bold);content.addView(t);return t;}
    TextInputEditText input(String hint){TextInputLayout l=new TextInputLayout(this);l.setHint(hint);l.setBoxBackgroundMode(TextInputLayout.BOX_BACKGROUND_OUTLINE);TextInputEditText e=new TextInputEditText(this);e.setTextSize(15);l.addView(e);content.addView(l,new LinearLayout.LayoutParams(-1,62));return e;}
    TextInputEditText input(String hint,boolean pass){TextInputEditText e=input(hint);if(pass)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}
    MaterialButton btn(String s){MaterialButton b=new MaterialButton(this);b.setText(s);b.setTextSize(15);b.setTextColor(Color.WHITE);b.setBackgroundColor(BLUE);b.setCornerRadius(18);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,56);p.setMargins(0,8,0,8);content.addView(b,p);return b;}
    void clear(String title){base(title);}
    void login(){clear("JobWork • Login");addText("Find trusted manufacturing vendors across Chennai",20,TEXT,true);addText("Customer and vendor accounts",14,MUTED,false);TextInputEditText email=input("Email");TextInputEditText pass=input("Password",true);MaterialButton b=btn("Login");b.setOnClickListener(v->auth.signInWithEmailAndPassword(email.getText().toString().trim(),pass.getText().toString()).addOnSuccessListener(x->{uid=x.getUser().getUid();loadRole();}).addOnFailureListener(e->toast(e.getMessage())));MaterialButton r=btn("Create account");r.setTextColor(BLUE);r.setBackgroundColor(Color.WHITE);r.setOnClickListener(v->register());addText("Demo admin: create a user then set role=admin in Firestore.",13,MUTED,false);}
    void register(){clear("Create JobWork account");Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Customer","Vendor"}));content.addView(sp,new LinearLayout.LayoutParams(-1,56));TextInputEditText name=input("Full name / Company name");TextInputEditText phone=input("Mobile number");TextInputEditText email=input("Email");TextInputEditText pass=input("Password",true);Spinner area=new Spinner(this);area.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,AREAS));content.addView(area,new LinearLayout.LayoutParams(-1,56));TextInputEditText services=input("Services (vendor only, comma separated)");MaterialButton b=btn("Register");b.setOnClickListener(v->auth.createUserWithEmailAndPassword(email.getText().toString().trim(),pass.getText().toString()).addOnSuccessListener(x->{uid=x.getUser().getUid();String rr=sp.getSelectedItem().toString().toLowerCase(Locale.ROOT);Map<String,Object> m=new HashMap<>();m.put("name",name.getText().toString());m.put("phone",phone.getText().toString());m.put("email",email.getText().toString());m.put("role",rr);m.put("area",area.getSelectedItem().toString());m.put("services",Arrays.asList(services.getText().toString().split(",")));m.put("createdAt",FieldValue.serverTimestamp());db.collection("users").document(uid).set(m).addOnSuccessListener(z->home()).addOnFailureListener(e->toast(e.getMessage()));}).addOnFailureListener(e->toast(e.getMessage())));MaterialButton l=btn("Back to Login");l.setTextColor(BLUE);l.setBackgroundColor(Color.WHITE);l.setOnClickListener(v->login());}
    void loadRole(){db.collection("users").document(uid).get().addOnSuccessListener(d->{role=d.exists()?String.valueOf(d.get("role")):"customer"; currentName=d.exists()?str(d,"name","User"):"User"; home();}).addOnFailureListener(e->home());}
    void home(){clear("JobWork");addText("Precision work. On time. Every time.",22,TEXT,true);addText("Chennai job-work marketplace",14,MUTED,false);MaterialCardView banner=card("Post a job → receive quotations → track production");content.addView(banner);if(role.equals("vendor")) vendorHome();else if(role.equals("admin")) adminHome();else customerHome();}
    MaterialCardView card(String s){MaterialCardView c=new MaterialCardView(this);c.setRadius(18);c.setCardElevation(2);TextView t=text(s,16,TEXT,true);t.setPadding(18,18,18,18);c.addView(t);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,70);p.setMargins(0,8,0,8);c.setLayoutParams(p);return c;}
    void customerHome(){MaterialButton a=btn("＋ New Job Work Enquiry");a.setOnClickListener(v->newEnquiry());MaterialButton s=btn("Find Vendors in Chennai");s.setOnClickListener(v->vendorSearch());MaterialButton q=btn("My Quotations");q.setOnClickListener(v->myQuotes());MaterialButton o=btn("My Orders & Tracking");o.setOnClickListener(v->myOrders());MaterialButton p=btn("Profile / Logout");p.setOnClickListener(v->profile());}
    void vendorHome(){addText("Vendor workspace",18,TEXT,true);MaterialButton e=btn("Open Job Enquiries");e.setOnClickListener(v->openEnquiries());MaterialButton q=btn("My Quotations");q.setOnClickListener(v->vendorQuotes());MaterialButton o=btn("Orders Received");o.setOnClickListener(v->myOrders());MaterialButton p=btn("Profile / Logout");p.setOnClickListener(v->profile());}
    void adminHome(){addText("Admin control center",18,TEXT,true);MaterialButton u=btn("Users / Vendors");u.setOnClickListener(v->adminUsers());MaterialButton e=btn("All Enquiries");e.setOnClickListener(v->adminCollection("enquiries","All Enquiries"));MaterialButton q=btn("All Quotes");q.setOnClickListener(v->adminCollection("quotes","All Quotes"));MaterialButton o=btn("All Orders");o.setOnClickListener(v->adminCollection("orders","All Orders"));MaterialButton p=btn("Profile / Logout");p.setOnClickListener(v->profile());}
    void newEnquiry(){clear("New Job Enquiry");TextInputEditText part=input("Part / Job name");Spinner cat=new Spinner(this);cat.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,SERVICES));content.addView(cat,new LinearLayout.LayoutParams(-1,56));TextInputEditText material=input("Material");TextInputEditText qty=input("Quantity");Spinner area=new Spinner(this);area.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,AREAS));content.addView(area,new LinearLayout.LayoutParams(-1,56));TextInputEditText notes=input("Specifications / drawing link (optional)");MaterialButton submit=btn("Submit Enquiry");submit.setOnClickListener(v->{Map<String,Object> m=new HashMap<>();m.put("customerId",uid);m.put("partName",part.getText().toString());m.put("category",cat.getSelectedItem().toString());m.put("material",material.getText().toString());m.put("quantity",qty.getText().toString());m.put("area",area.getSelectedItem().toString());m.put("notes",notes.getText().toString());m.put("status","OPEN");m.put("createdAt",FieldValue.serverTimestamp());db.collection("enquiries").add(m).addOnSuccessListener(x->{toast("Enquiry posted");home();}).addOnFailureListener(e->toast(e.getMessage()));});}
    void vendorSearch(){clear("Find Vendors • Chennai");Spinner area=new Spinner(this);area.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,AREAS));content.addView(area,new LinearLayout.LayoutParams(-1,56));Spinner service=new Spinner(this);service.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,SERVICES));content.addView(service,new LinearLayout.LayoutParams(-1,56));MaterialButton go=btn("Search Vendors");go.setOnClickListener(v->db.collection("users").whereEqualTo("role","vendor").whereEqualTo("area",area.getSelectedItem().toString()).whereArrayContains("services",service.getSelectedItem().toString()).get().addOnSuccessListener(snap->{clear("Vendors in "+area.getSelectedItem());for(DocumentSnapshot d:snap){String name=str(d,"name","Vendor");String phone=str(d,"phone","");String services=str(d,"services","");MaterialCardView c=card(name+"\n★ "+str(d,"rating","New")+"  •  "+services);c.setOnClickListener(x->contactVendor(phone,name));content.addView(c);}}).addOnFailureListener(e->toast(e.getMessage())));}
    void contactVendor(String phone,String name){MaterialButton w=btn("WhatsApp "+name);w.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/91"+phone.replaceAll("\\D",""))));}catch(Exception e){toast("WhatsApp not installed");}});MaterialButton c=btn("Call vendor");c.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone))));}
    void openEnquiries(){clear("Open Job Enquiries");db.collection("enquiries").whereEqualTo("status","OPEN").orderBy("createdAt",Query.Direction.DESCENDING).limit(30).get().addOnSuccessListener(snap->{for(DocumentSnapshot d:snap){MaterialCardView c=card(str(d,"partName","Job")+"\n"+str(d,"category","")+" • "+str(d,"area","")+"\nQty: "+str(d,"quantity",""));c.setOnClickListener(v->quoteForm(d));content.addView(c);}}).addOnFailureListener(e->toast(e.getMessage()));}
    void quoteForm(DocumentSnapshot enq){clear("Submit Quotation");addText(str(enq,"partName","Job"),20,TEXT,true);TextInputEditText price=input("Total quote ₹");TextInputEditText days=input("Delivery days");TextInputEditText terms=input("Payment terms");TextInputEditText note=input("Vendor note");MaterialButton b=btn("Send Quote");b.setOnClickListener(v->{Map<String,Object> q=new HashMap<>();q.put("enquiryId",enq.getId());q.put("customerId",str(enq,"customerId",""));q.put("vendorId",uid);q.put("vendorName",getVendorName());q.put("price",price.getText().toString());q.put("days",days.getText().toString());q.put("terms",terms.getText().toString());q.put("note",note.getText().toString());q.put("status","SENT");q.put("createdAt",FieldValue.serverTimestamp());db.collection("quotes").add(q).addOnSuccessListener(x->{toast("Quotation sent");home();}).addOnFailureListener(e->toast(e.getMessage()));});}
    String getVendorName(){return currentName;}
    void myQuotes(){clear("My Quotations");db.collection("quotes").whereEqualTo("customerId",uid).orderBy("createdAt",Query.Direction.DESCENDING).limit(50).get().addOnSuccessListener(s->{for(DocumentSnapshot d:s){MaterialCardView c=card("₹ "+str(d,"price","0")+" • "+str(d,"vendorName","Vendor")+"\nDelivery: "+str(d,"days","-")+" days • "+str(d,"status","SENT"));if("SENT".equals(str(d,"status",""))){c.setOnClickListener(v->acceptQuote(d));}content.addView(c);}}).addOnFailureListener(e->toast(e.getMessage()));}
    void vendorQuotes(){clear("My Quotations");db.collection("quotes").whereEqualTo("vendorId",uid).orderBy("createdAt",Query.Direction.DESCENDING).limit(50).get().addOnSuccessListener(s->{for(DocumentSnapshot d:s)content.addView(card("₹ "+str(d,"price","0")+" • "+str(d,"status","SENT")+"\nDelivery: "+str(d,"days","-")+" days"));}).addOnFailureListener(e->toast(e.getMessage()));}
    void acceptQuote(DocumentSnapshot q){new AlertDialog.Builder(this).setTitle("Accept quotation?").setMessage("₹ "+str(q,"price","0")+" from "+str(q,"vendorName","Vendor")).setNegativeButton("Cancel",null).setPositiveButton("Accept",(d,w)->{Map<String,Object> o=new HashMap<>();o.put("quoteId",q.getId());o.put("customerId",uid);o.put("vendorId",str(q,"vendorId",""));o.put("price",str(q,"price","0"));o.put("status","CONFIRMED");o.put("createdAt",FieldValue.serverTimestamp());db.collection("orders").add(o).addOnSuccessListener(x->{db.collection("quotes").document(q.getId()).update("status","ACCEPTED");toast("Order created");myOrders();});}).show();}
    void myOrders(){clear("Orders & Tracking");Query q=role.equals("vendor")?db.collection("orders").whereEqualTo("vendorId",uid):db.collection("orders").whereEqualTo("customerId",uid);q.get().addOnSuccessListener(s->{for(DocumentSnapshot d:s){MaterialCardView c=card("Order #"+d.getId().substring(0,6).toUpperCase(Locale.ROOT)+"\n₹ "+str(d,"price","0")+" • "+str(d,"status","CONFIRMED"));c.setOnClickListener(v->orderDetails(d));content.addView(c);}}).addOnFailureListener(e->toast(e.getMessage()));}
    void orderDetails(DocumentSnapshot d){clear("Order Tracking");addText("Order #"+d.getId(),18,TEXT,true);String[] states={"CONFIRMED","MATERIAL_RECEIVED","IN_PRODUCTION","QUALITY_CHECK","DISPATCHED","DELIVERED"};for(String st:states)content.addView(card((st.equals(str(d,"status","CONFIRMED"))?"● ":"○ ")+st.replace('_',' ')));if(role.equals("vendor")){MaterialButton u=btn("Mark Next Stage");u.setOnClickListener(v->{int i=0;for(int x=0;x<states.length;x++)if(states[x].equals(str(d,"status","CONFIRMED")))i=x;String n=states[Math.min(i+1,states.length-1)];db.collection("orders").document(d.getId()).update("status",n).addOnSuccessListener(x->db.collection("orders").document(d.getId()).get().addOnSuccessListener(this::orderDetails));});}MaterialButton pay=btn("Pay / Collect via UPI");pay.setOnClickListener(v->upiPay(str(d,"price","0"),"JobWork Order"));}
    void upiPay(String amount,String note){try{Uri u=Uri.parse("upi://pay?pa=jobwork@upi&pn=JobWork&am="+amount+"&cu=INR&tn="+Uri.encode(note));startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){toast("No UPI app found");}}
    void adminUsers(){clear("Users / Vendors");db.collection("users").limit(100).get().addOnSuccessListener(s->{for(DocumentSnapshot d:s){MaterialCardView c=card(str(d,"name","User")+"\n"+str(d,"role","customer")+" • "+str(d,"area",""));content.addView(c);}});}
    void adminCollection(String col,String title){clear(title);db.collection(col).limit(100).get().addOnSuccessListener(s->{for(DocumentSnapshot d:s)content.addView(card(d.getId()+"\n"+d.getData()));});}
    void profile(){clear("Profile");db.collection("users").document(uid).get().addOnSuccessListener(d->{content.addView(card(str(d,"name","User")+"\n"+str(d,"email","")+"\n"+str(d,"phone","")+"\nRole: "+role+"\nArea: "+str(d,"area","")));});MaterialButton out=btn("Logout");out.setOnClickListener(v->{auth.signOut();login();});}
    String str(DocumentSnapshot d,String k,String def){Object o=d.get(k);return o==null?def:String.valueOf(o);}
    void toast(String s){Toast.makeText(this,s==null?"Something went wrong":s,Toast.LENGTH_LONG).show();}
}
